In [2]:
import numpy as np

### 
对于ndarray结构来说，里面所有的元素必须是同一类型的如果不是的话，会自动的向下进行转换


In [5]:
tang_list = [1,2,3,4,5.0]
tang_array = np.array(tang_list)
tang_array

array([1., 2., 3., 4., 5.])

In [4]:
type(tang_array)


numpy.ndarray

In [6]:
tang_array.itemsize

8

In [7]:
tang_array.size

5

In [8]:
tang_array.shape


(5,)

In [9]:
tang_array.ndim

1

In [10]:
tang_array.fill(0)
tang_array

array([0., 0., 0., 0., 0.])

In [11]:
tang_array[1:3]

array([0., 0.])

### 矩阵格式（多维）

In [13]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
tang_array[1,1]

5

In [15]:
tang_array[:,1]

array([2, 5, 8])

In [16]:
tang_array[1]

array([4, 5, 6])

In [17]:
tang_array2 = tang_array
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
tang_array2 = tang_array.copy()
tang_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
tang_array2[1,1] = 1000
tang_array2

array([[   1,    2,    3],
       [   4, 1000,    6],
       [   7,    8,    9]])

In [20]:
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 用于取数，两个相乘

In [22]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
mask = np.array([0,0,0,0,1,1,0,1,0,1],dtype = bool)
mask

array([False, False, False, False,  True,  True, False,  True, False,
        True])

In [24]:
tang_array[mask]

array([40, 50, 70, 90])

In [27]:
random_array = np.random.rand(10)
random_array

array([0.48891083, 0.24307782, 0.50777307, 0.20835376, 0.68076635,
       0.04129889, 0.82620472, 0.36146194, 0.19207441, 0.22718214])

In [28]:
np.where(tang_array > 30)#定位索引

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

### 数组类型

In [30]:
tang_array = np.array([1,2,3,4,5],dtype = np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [31]:
tang_array.nbytes

20

In [33]:
tang_array = np.array([1,10,3.5,'str'],dtype = np.object)
tang_array

C:\Users\BAOfanTing\AppData\Local\Temp\ipykernel_26540\3813702755.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  tang_array = np.array([1,10,3.5,'str'],dtype = np.object)


array([1, 10, 3.5, 'str'], dtype=object)

In [34]:
tang_array *2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [ ]:
tang_array = np.arra