In [3]:
import numpy as np
tang_array = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [4]:
np.sort(tang_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [5]:
np.sort(tang_array,axis = 0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [6]:
np.argsort(tang_array)#返回的是排序的的索引值

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [7]:
tang_array = np.linspace(0,10,10)
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
values = np.array([2.5,6.5,9.8])#找到出入的位置
np.searchsorted(tang_array,values)

array([3, 6, 9], dtype=int64)

In [11]:
tang_array = np.array([[1,0,6],[1,7,0],[2,3,1],[2,4,0]])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [16]:
index = np.lexsort([-1*tang_array[:,0],tang_array[:,2]])
index

array([3, 1, 2, 0], dtype=int64)

In [17]:
tang_array = tang_array[index]
tang_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])