### 数组形状操作

In [1]:
import numpy as np

In [2]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
tang_array.shape

(10,)

In [4]:
tang_array.shape = 2,5

In [5]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

新增维度

In [9]:
tang_array = np.arange(10)
tang_array = tang_array[np.newaxis,:]
tang_array.shape

(1, 10)

In [10]:
tang_array = tang_array.squeeze()
tang_array.shape

(10,)

In [11]:
tang_array.shape = 2,5
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

转置操作，原数不变

In [12]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 数组的连接

In [14]:
a = np.array([[132,456,789],[125,454,8789]])
b = np.array([[12,45,89],[15,44,889]])

c = np.concatenate((a,b))
c

array([[ 132,  456,  789],
       [ 125,  454, 8789],
       [  12,   45,   89],
       [  15,   44,  889]])

In [15]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 132,  456,  789,   12,   45,   89],
       [ 125,  454, 8789,   15,   44,  889]])

In [16]:
np.vstack((a,b))

array([[ 132,  456,  789],
       [ 125,  454, 8789],
       [  12,   45,   89],
       [  15,   44,  889]])

In [17]:
np.hstack((a,b))

array([[ 132,  456,  789,   12,   45,   89],
       [ 125,  454, 8789,   15,   44,  889]])

In [18]:
a

array([[ 132,  456,  789],
       [ 125,  454, 8789]])

In [19]:
a.flatten()

array([ 132,  456,  789,  125,  454, 8789])