In [3]:
import numpy as np


In [5]:
x = np.array([5,5])
y = np.array([2,2])

In [6]:
np.multiply(x,y)

array([10, 10])

矩阵相乘

In [7]:
np.dot(x,y)

20

In [10]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print(x*y)

[[1 2 3]
 [4 5 6]]


In [11]:
x = np.array([1,1,1])
y = np.array([1,1,1])
x == y

array([ True,  True,  True])

In [12]:
x = np.array([1,1,1,4])
y = np.array([1,1,1])
x == y

C:\Users\BAOfanTing\AppData\Local\Temp\ipykernel_1924\3642601902.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  x == y


False