### np的随机模块

In [1]:
import numpy as np

In [2]:
#所有制都是0-1，浮点数
np.random.rand(3,2)

array([[0.59357327, 0.76053693],
       [0.27017772, 0.88354974],
       [0.29585445, 0.58799949]])

In [4]:
#锁机整数，左闭右开
np.random.randint(10,size = (5,4))

array([[4, 3, 3, 2],
       [8, 1, 4, 6],
       [8, 4, 8, 7],
       [0, 2, 1, 1],
       [0, 1, 6, 9]])

In [5]:
np.random.random_sample()

0.7576339582584967

In [6]:
np.random.randint(0,10,3)

array([8, 8, 4])

In [14]:
np.set_printoptions(precision = 3)#设置小数点

In [15]:
mu,sigma = 0,0.1
n = np.random.normal(mu,sigma,10)
n

array([ 0.024, -0.036, -0.017,  0.077, -0.202,  0.103, -0.12 ,  0.059,
        0.232,  0.103])

### 洗牌

In [18]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.random.shuffle(tang_array)
tang_array

array([8, 3, 4, 7, 1, 0, 9, 2, 6, 5])

### 随机的种子

In [24]:
np.random.seed(0)

In [25]:
mu,sigma = 0,0.1
n = np.random.normal(mu,sigma,10)
n

array([ 0.176,  0.04 ,  0.098,  0.224,  0.187, -0.098,  0.095, -0.015,
       -0.01 ,  0.041])