In [1]:
import numpy as np


In [6]:
%%writefile tang.txt
1 2 3 4 5 
7 8 9 9 10

Overwriting tang.txt


In [4]:
data = []
with open('tang.txt') as f:
    for line in f:
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

C:\Users\BAOfanTing\AppData\Local\Temp\ipykernel_38324\3084233582.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array(data)


array([list([1.0, 2.0, 3.0, 4.0, 5.0]), list([7.0, 8.0, 9.0, 9.0])],
      dtype=object)

In [7]:
data = np.loadtxt('tang.txt')
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 7.,  8.,  9.,  9., 10.]])

In [8]:
%%writefile tang2.txt
1,2,3,4,5 
7,8,9,9,10

Writing tang2.txt


In [9]:
data = np.loadtxt('tang2.txt',delimiter = ',')
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 7.,  8.,  9.,  9., 10.]])

In [10]:
%%writefile tang3.txt
x,y,z,w,a,b
1,2,3,4,5 
7,8,9,9,10

Writing tang3.txt


In [12]:
data = np.loadtxt('tang2.txt',delimiter = ',',skiprows = 0)
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 7.,  8.,  9.,  9., 10.]])

* tang2.txt’:路径最好放到和代码一起
* skiprows :去掉几行
* delimiter = ',’:分隔符
* usecols = (0，1,4) :指定使用哪几列

In [13]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.savetxt('tang_4.txt',tang_array)

In [14]:
np.savetxt('tang_4.txt',tang_array,fmt = '%d')

In [15]:
np.savetxt('tang_4.txt',tang_array,fmt = '%d',delimiter = ' ')

### 读array结构


In [16]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy',tang_array)

In [17]:
tang = np.load('tang_array.npy')
tang

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
tang_array2 = np.arange(10)
tang_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.savez('tang.npz',a = tang_array,b = tang_array2)

In [23]:
data= np.load('tang.npz')

In [24]:
data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x000001B6A03956A0>)

In [25]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])