### 打印当前np版本

In [2]:
import numpy as np
print(np.__version__)

1.21.5


### 构造一个全零的矩阵，并打印其占用的内存大小


In [2]:
z = np.zeros((5,5))
print('%d bytes'% (z.size * z.itemsize))

200 bytes


### 打印一个函数的帮助文档，比如numpy.add

In [3]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 创建一个10-49的数组，并将其倒序排列


In [4]:
a = np.arange(10,50,1)
a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 找到一个数组中不为0的索引

In [5]:
np.nonzero([1,2,3,4,0,0,0,5])

(array([0, 1, 2, 3, 7], dtype=int64),)

### 随机构造一个3*3矩阵，并打印其中最大与最小值

In [6]:
tang_array = np.random.random((3,3))
tang_array.min()
tang_array.max()

0.9871180221973601

### 构造一个5*5的矩阵，令其值都为1，并在最外层加上一圈0

In [9]:
tang_array = np.ones((5,5))
tang_array = np.pad(tang_array,pad_width = 1,mode = 'constant',constant_values = 0)
tang_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### 构建一个shape为(6，7，8）的矩阵，并找到第100个元素的索引值

In [3]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### 对一个5*5的矩阵做归一化操作


In [5]:
tang_array = np.random.random((5,5))
tang_max = tang_array.max()
tang_min = tang_array.min()
tang_array = (tang_array - tang_min)/(tang_array - tang_max)
tang_array

C:\Users\BAOfanTing\AppData\Local\Temp\ipykernel_5316\2744359820.py:4: RuntimeWarning: divide by zero encountered in true_divide
  tang_array = (tang_array - tang_min)/(tang_array - tang_max)


array([[ -0.39790777,  -9.29044285,  -0.23449454,  -0.21039478,
         -0.55391001],
       [ -8.27913882,  -0.54808152,  -0.0450577 ,  -2.32745244,
         -0.33572775],
       [ -0.        ,  -0.77631084,  -1.1614139 ,  -0.222405  ,
         -0.64575061],
       [         inf,  -2.53008052,  -0.33052741,  -4.18244624,
        -12.12039978],
       [ -1.01047127,  -2.96113073,  -0.66824917,  -0.55976421,
         -0.66285732]])

### 找到两个数组中相同的值

In [8]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[2 8 9]


### 得到今天明天昨天的日期

In [9]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tommorow)

2022-08-16
2022-08-17
2022-08-18


### 得到一个月中的所有天

In [10]:
np.arange('2022-08','2022-09',dtype = 'datetime64[D]')

array(['2022-08-01', '2022-08-02', '2022-08-03', '2022-08-04',
       '2022-08-05', '2022-08-06', '2022-08-07', '2022-08-08',
       '2022-08-09', '2022-08-10', '2022-08-11', '2022-08-12',
       '2022-08-13', '2022-08-14', '2022-08-15', '2022-08-16',
       '2022-08-17', '2022-08-18', '2022-08-19', '2022-08-20',
       '2022-08-21', '2022-08-22', '2022-08-23', '2022-08-24',
       '2022-08-25', '2022-08-26', '2022-08-27', '2022-08-28',
       '2022-08-29', '2022-08-30', '2022-08-31'], dtype='datetime64[D]')

### 得到一个数的整数部分

In [11]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([0., 8., 5., 9., 2., 1., 8., 5., 5., 0.])

### 构造一个数组，让它不能改变

In [12]:
z = np.zeros(5)
z.flags.writeable = False
z[1] = 1

ValueError: assignment destination is read-only

### 打印大数据的部分值，全部值

In [16]:
np.set_printoptions(threshold = 5)# = np.inf全部打映
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### 找到在一个数组中，最接近一个数的索引

In [17]:
z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(z-v)).argmin()
print(z[index])

22.733998908730246
23


### 32位float类型和32位int类型转换

In [18]:
z = np.arange(10,dtype = np.int32)
print(z.dtype)
z = z.astype(np.float32)
print(z.dtype)

int32
float32


### 打印数组元素位置坐标与数值

In [20]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 按照数组的某一列进行排序

In [22]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])#按第二列排序，然后返回下标

[[5 6 0]
 [4 6 6]
 [3 8 5]]
[[5 6 0]
 [4 6 6]
 [3 8 5]]


### 统计数组中每个数值出现的次数

In [23]:
z = np.array([1,1,1,2,2,34,4,4,7,8,9,7,8])
np.bincount(z)

array([0, 3, 2, ..., 0, 0, 1], dtype=int64)

### 如何对一个四维数组的最后两维来求和

In [24]:
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis = (-2,-1))
res

array([[72, 86, 89, 56],
       [52, 89, 55, 60],
       [64, 63, 60, 59],
       [63, 74, 77, 46]])

### 交换矩阵中的两行

In [27]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
z

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 找到一个数组中最常出现的数字

In [29]:
z = np.random.randint(0,10,50)
print(np.bincount(z).argmax())

8


### 快速查找TOP K

In [31]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argpartition(-z,n)[:n]])

[9999 9998 9997 9995 9996]


### 去除掉一个数组中，所有元素都相同的数据

In [38]:
np.set_printoptions(threshold = np.inf)# 
z = np.random.randint(0,10,(10,3))
z


array([[1, 2, 0],
       [4, 7, 1],
       [8, 8, 1],
       [5, 4, 0],
       [4, 5, 9],
       [4, 0, 6],
       [6, 5, 8],
       [2, 6, 0],
       [7, 2, 4],
       [5, 5, 7]])

In [37]:
e = np.all(z[:,1:] == z[:,:-1],axis = 1)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,3,4,5])
np.all(a==b)

False